run:
  concurrency: 16
  timeout: 5m
  tests: false
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - errcheck
    - forcetypeassert
    - gofumpt
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - nakedret
    - nolintlint
    - staticcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  nolintlint:
    allow-leading-space: true

issues:
  exclude-rules:
    - path: x/scheduler/client/cli/tx_hook
      text: "SA1019: cli.FlagDescription is deprecated: only used for v1beta1 legacy proposals."
    - path: x/scheduler/client/cli/tx_hook
      text: "SA1019: cli.FlagProposal is deprecated: only used for v1beta1 legacy proposals."
