kujirad tx gov submit-proposal software-upgrade v0.5.0 \
    --upgrade-height 2055000  \
    --upgrade-info "https://github.com/Team-Kujira/core/releases/tag/v0.5.0, commit hash 89470bd1ec8e3dd8cd3e8c7a9856e527b2c7f079" \
    --deposit 10000000ukuji \
    --from kujira-testnet \
    --fees 250ukuji \
    --title "Upgrade to core v0.5.0" \
    --description "This will upgrade the chain to version 0.5.0, adding x/oracle to provide protocol developers with external price feeds, available on-chain" \
    --chain-id harpoon-4 \
    --keyring-backend os \
    --node https://rpc.harpoon.kujira.setten.io:443