on: [push, pull_request]
name: Build, Test, Tidy
jobs:

  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go build ./...

## Reinstate this ASAP!!
  # test:
  #   runs-on: ubuntu-latest
  #   name: test
  #   steps:
  #   - name: Install Go
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: 1.18
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Test
  #     run: go test ./...

# Use --check or --exit-code when available (Go 1.19?)
# https://github.com/golang/go/issues/27005
  tidy:
    runs-on: ubuntu-latest
    name: tidy
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: |
          go mod tidy
          CHANGES_IN_REPO=$(git status --porcelain)
          if [[ -n "$CHANGES_IN_REPO" ]]; then
            echo "Repository is dirty. Showing 'git status' and 'git --no-pager diff' for debugging now:"
            git status && git --no-pager diff
            exit 1
          fi
