syntax = "proto3";
package kujira.oracle;

import "gogoproto/gogo.proto";
import "cosmos/msg/v1/msg.proto";
import "kujira/oracle/oracle.proto";

option go_package = "github.com/Team-Kujira/core/x/oracle/types";

// Msg defines the oracle Msg service.
service Msg {
  // AddRequiredDenom adds a new price to the required list of prices
  rpc AddRequiredDenoms(MsgAddRequiredDenoms) returns (MsgAddRequiredDenomsResponse);

  // RemoveRequiredDenom removes a price from the required list of prices
  rpc RemoveRequiredDenoms(MsgRemoveRequiredDenoms) returns (MsgRemoveRequiredDenomsResponse);

  // UpdateParams sets new module params
  rpc UpdateParams(MsgUpdateParams) returns (MsgUpdateParamsResponse);
}

// MsgAddRequiredDenom represents a message to add a denom to the whitelist
message MsgAddRequiredDenoms {
  option (cosmos.msg.v1.signer) = "authority";

  string authority = 1 [(gogoproto.moretags) = "yaml:\"authority\""];
  repeated string symbols = 2 [ (gogoproto.moretags) = "yaml:\"symbols\"" ];
}

// MsgAddRequiredDenomResponse defines the Msg/AddRequiredDenom response type.
message MsgAddRequiredDenomsResponse {}

// MsgRemoveRequiredDenom represents a message to remove a denom from the whitelist
message MsgRemoveRequiredDenoms {
  option (cosmos.msg.v1.signer) = "authority";

  string authority = 1 [ (gogoproto.moretags) = "yaml:\"authority\"" ];
  repeated string symbols = 2 [ (gogoproto.moretags) = "yaml:\"symbols\"" ];
}

// MsgRemoveRequiredDenomResponse defines the Msg/RemoveRequiredDenom response type.
message MsgRemoveRequiredDenomsResponse {}

message MsgUpdateParams {
  option (cosmos.msg.v1.signer) = "authority";

  string authority = 1 [(gogoproto.moretags) = "yaml:\"authority\""];
  Params params = 2 [(gogoproto.moretags) = "yaml:\"params\""];
}

// MsgUpdateParamsResponse defines the Msg/UpdateParams response type.
message MsgUpdateParamsResponse {}